### ISSUE TITLE
Configuration for Mongoid

### ISSUE THREAD

**Issue by reedlaw** [freerange/oauth2-provider#25]
It took me a while to figure out that to activate the Mongoid backend I had to add this to my environment's config files:

```
  config.oauth2_provider.backend = :mongoid
```

Maybe this should go in the README?

**Comment by floehopper** [comment]
**DEPRECATION NOTICE**: This project is no longer supported. [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) or [`Songkick::Oauth2::Provider`](https://github.com/songkick/oauth2-provider) might offer the functionality you're looking for. We're keeping this repository around in case anyone is still relying on it, but note that there are a number of security vulnerabilities in the gem's dependencies as things stand, so use it at your own risk. If anyone wants to take over ownership of the repo, please [get in touch](http://gofreerange.com/contact).
