### ISSUE TITLE
Handle Basic client authorization gracefully

### ISSUE THREAD

**Issue by tomafro** [freerange/oauth2-provider#30]
Currently Basic auth is only available to clients using the `client_credentials` grant type.  It should be made available to all requests where the client needs authorization.

**Comment by floehopper** [comment]
**DEPRECATION NOTICE**: This project is no longer supported. [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) or [`Songkick::Oauth2::Provider`](https://github.com/songkick/oauth2-provider) might offer the functionality you're looking for. We're keeping this repository around in case anyone is still relying on it, but note that there are a number of security vulnerabilities in the gem's dependencies as things stand, so use it at your own risk. If anyone wants to take over ownership of the repo, please [get in touch](http://gofreerange.com/contact).
