### ISSUE TITLE
OAuth2 Draft 11 out of date

### ISSUE THREAD

**Issue by thatothermitch** [freerange/oauth2-provider#37]
oauth2-provider was originally designed to support draft 11, but the spec has obviously moved forward since then.

Do you think it would make sense to add explicit support for a later draft? If so, how would you like to go about it?

**Comment by floehopper** [comment]
**DEPRECATION NOTICE**: This project is no longer supported. [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) or [`Songkick::Oauth2::Provider`](https://github.com/songkick/oauth2-provider) might offer the functionality you're looking for. We're keeping this repository around in case anyone is still relying on it, but note that there are a number of security vulnerabilities in the gem's dependencies as things stand, so use it at your own risk. If anyone wants to take over ownership of the repo, please [get in touch](http://gofreerange.com/contact).
