### ISSUE TITLE
undefined method `collection_name='  with the latest Mongoid 3 (cb1312e5385c1c9d142337174b904ef9c971d51b)

### ISSUE THREAD

**Issue by burgalon** [freerange/oauth2-provider#41]
When upgrading to the latest Mongoid 3 (cb1312e5385c1c9d142337174b904ef9c971d51b) it seems like the "collection_name" was modified in Mongoid 3 and so the application would fails with the following error:
<verbatim>
/Users/alon/git/oauth2-provider/lib/oauth2/provider/models/mongoid.rb:25:in `activate': undefined method`collection_name=' for OAuth2::Provider::Models::Mongoid::Client:Class (NoMethodError)
    from /Users/alon/git/oauth2-provider/lib/oauth2/provider.rb:38:in `activate'
    from /Users/alon/git/oauth2-provider/lib/oauth2/provider/rails.rb:24:in`block in class:Railtie'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/initializable.rb:30:in`run'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/initializable.rb:54:in`each'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/application.rb:136:in`initialize!'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/alon/git/myapp-server/config/environment.rb:48:in`<top (required)>'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in`block in require'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in`require'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/application.rb:103:in `require_environment!'
    from /Users/alon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.1/lib/rails/commands.rb:40:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'
</verbatim>

**Comment by floehopper** [comment]
**DEPRECATION NOTICE**: This project is no longer supported. [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) or [`Songkick::Oauth2::Provider`](https://github.com/songkick/oauth2-provider) might offer the functionality you're looking for. We're keeping this repository around in case anyone is still relying on it, but note that there are a number of security vulnerabilities in the gem's dependencies as things stand, so use it at your own risk. If anyone wants to take over ownership of the repo, please [get in touch](http://gofreerange.com/contact).
